### ISSUE TITLE
Setting Gallery Page Options causes wordpress to stop working

### ISSUE THREAD

**Issue by fryfrog** [digitaldonkey/wpg3#2]
I'm trying to get your wpg3 working with my wordpress + gallery3, but I'm having issues at the last portion.

I'm able to complete the Basic WPG3 Options step and save, which then opens up the rest of the options. I enter the right values for XHTTP Options (except I'm not sure what "Rest API Key" is so I leave it blank) and then save, which seems to work.

Finally, when I try to setup the page my wordpress stops working. I _think_ it goes into a redirect loop, but I'm not entirely sure as my error log is strangely silent on the matter.

I then have to delete the wpg3_options row on the wp_options table and restart apache to get things working again.

I'd be happy to work with you over email, IM or what ever. And I can provide logs or anything else as well.

**Comment by jlev** [comment]
Same issue here, although for me it only happens after I set a gallery page. After that, I get a 504 gateway timeout error. @digitaldonkey is this the caching issue you mentioned at http://wordpress.org/support/topic/plugin-wpg2-wpg3/page/3#post-2105450 

Is there anything we can do to debug or fix this behavior?

**Comment by fryfrog** [comment]
So old, closing.
